spring.application.name=wave

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/wave
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:mohith123}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=WaveSecureAppSecretKeyForJWTTokenGeneration2026MustBeLongEnoughForHS512Algorithm!!
jwt.expiration=86400000

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=./uploads

# Server
server.port=8080